export const testMovies = [
  {
    country: '',
    director: '',
    duration: 77,
    year: '',
    description: '',
    image: '01.jpg',
    trailerLink: '',
    thumbnail: '01_preview.jpg',
    owner: '12344',
    movieId: 0,
    nameRU: '33 слова о дизайне',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 60,
    year: '',
    description: '',
    image: '02.jpg',
    trailerLink: '',
    thumbnail: '02_preview.jpg',
    owner: '12345',
    movieId: 1,
    nameRU: 'Киноальманах «100 лет дизайна»',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 30,
    year: '',
    description: '',
    image: '03.jpg',
    trailerLink: '',
    thumbnail: '03_preview.jpg',
    owner: '12344',
    movieId: 2,
    nameRU: 'В погоне за Бенкси',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 80,
    year: '',
    description: '',
    image: '04.jpg',
    trailerLink: '',
    thumbnail: '04_preview.jpg',
    owner: '12344',
    movieId: 3,
    nameRU: 'Баския: Взрыв реальности',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 51,
    year: '',
    description: '',
    image: '05.jpg',
    trailerLink: '',
    thumbnail: '05_preview.jpg',
    owner: '12344',
    movieId: 4,
    nameRU: 'Бег это свобода',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 72,
    year: '',
    description: '',
    image: '06.jpg',
    trailerLink: '',
    thumbnail: '06_preview.jpg',
    owner: '12345',
    movieId: 5,
    nameRU: 'Книготорговцы',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 89,
    year: '',
    description: '',
    image: '07.jpg',
    trailerLink: '',
    thumbnail: '07_preview.jpg',
    owner: '12344',
    movieId: 6,
    nameRU: 'Когда я думаю о Германии ночью',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 67,
    year: '',
    description: '',
    image: '08.jpg',
    trailerLink: '',
    thumbnail: '08_preview.jpg',
    owner: '12344',
    movieId: 7,
    nameRU: 'Gimme Danger: История Игги и The Stooges',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 119,
    year: '',
    description: '',
    image: '09.jpg',
    trailerLink: '',
    thumbnail: '09_preview.jpg',
    owner: '12344',
    movieId: 8,
    nameRU: 'Дженис: Маленькая девочка грустит',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 47,
    year: '',
    description: '',
    image: '10.jpg',
    trailerLink: '',
    thumbnail: '10_preview.jpg',
    owner: '12345',
    movieId: 9,
    nameRU: 'Соберись перед прыжком',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 96,
    year: '',
    description: '',
    image: '11.jpg',
    trailerLink: '',
    thumbnail: '11_preview.jpg',
    owner: '12345',
    movieId: 10,
    nameRU: 'Пи Джей Харви: A dog called money',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 129,
    year: '',
    description: '',
    image: '12.jpg',
    trailerLink: '',
    thumbnail: '12_preview.jpg',
    owner: '12344',
    movieId: 11,
    nameRU: 'По волнам: Искусство звука в кино',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 77,
    year: '',
    description: '',
    image: '01.jpg',
    trailerLink: '',
    thumbnail: '01_preview.jpg',
    owner: '12344',
    movieId: 12,
    nameRU: '33 слова о дизайне',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 60,
    year: '',
    description: '',
    image: '02.jpg',
    trailerLink: '',
    thumbnail: '02_preview.jpg',
    owner: '12344',
    movieId: 13,
    nameRU: 'Киноальманах «100 лет дизайна»',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 30,
    year: '',
    description: '',
    image: '03.jpg',
    trailerLink: '',
    thumbnail: '03_preview.jpg',
    owner: '12344',
    movieId: 14,
    nameRU: 'В погоне за Бенкси',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 80,
    year: '',
    description: '',
    image: '04.jpg',
    trailerLink: '',
    thumbnail: '04_preview.jpg',
    owner: '12344',
    movieId: 15,
    nameRU: 'Баския: Взрыв реальности',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 51,
    year: '',
    description: '',
    image: '05.jpg',
    trailerLink: '',
    thumbnail: '05_preview.jpg',
    owner: '12344',
    movieId: 16,
    nameRU: 'Бег это свобода',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 72,
    year: '',
    description: '',
    image: '06.jpg',
    trailerLink: '',
    thumbnail: '06_preview.jpg',
    owner: '12344',
    movieId: 17,
    nameRU: 'Книготорговцы',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 89,
    year: '',
    description: '',
    image: '07.jpg',
    trailerLink: '',
    thumbnail: '07_preview.jpg',
    owner: '12344',
    movieId: 18,
    nameRU: 'Когда я думаю о Германии ночью',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 67,
    year: '',
    description: '',
    image: '08.jpg',
    trailerLink: '',
    thumbnail: '08_preview.jpg',
    owner: '12344',
    movieId: 19,
    nameRU: 'Gimme Danger: История Игги и The Stooges',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 119,
    year: '',
    description: '',
    image: '09.jpg',
    trailerLink: '',
    thumbnail: '09_preview.jpg',
    owner: '12344',
    movieId: 20,
    nameRU: 'Дженис: Маленькая девочка грустит',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 47,
    year: '',
    description: '',
    image: '10.jpg',
    trailerLink: '',
    thumbnail: '10_preview.jpg',
    owner: '12344',
    movieId: 21,
    nameRU: 'Соберись перед прыжком',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 96,
    year: '',
    description: '',
    image: '11.jpg',
    trailerLink: '',
    thumbnail: '11_preview.jpg',
    owner: '12344',
    movieId: 22,
    nameRU: 'Пи Джей Харви: A dog called money',
    nameEN: ''
  },
  {
    country: '',
    director: '',
    duration: 129,
    year: '',
    description: '',
    image: '12.jpg',
    trailerLink: '',
    thumbnail: '12_preview.jpg',
    owner: '12344',
    movieId: 23,
    nameRU: 'По волнам: Искусство звука в кино',
    nameEN: ''
  }
];
